/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Client */

#ifndef _Included_Client
#define _Included_Client
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Client
 * Method:    MakeATest
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Client_MakeATest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
